class AppTexts {
  static String currency = 'N'; // '₦';
  static String welcomeTxt = "";
  static const String unableToConnect =
      'Unable to connect to the server. Kindly try again';
  static const String timeout =
      'Request timeout: Bad internet connection, try again';
  static const String noInternet =
      'No active internet connection, Kindly try again!';
  static Pattern emailVerificationPattern =
      r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$';
  // static const String privacyPolicy =
  //     " Privacy Policy for Medi Mart. We, BENEVOLENCE TEAM, are commited to protecting the privacy and secrity of our users. This Privacy Policy explain how we collect, use, and disclose information about users of our application. We collect information about users in the following ways: Information you provide: When you use our application, we may collect personal information that you provide, such as your name, email address, phone number, and other contact information. We may also collect information about your location, interests, and preferences. Information we collect automatically: We may collect certain information automatically when you use our application, such as your device information, IP address, and usage information. How we use information We use the information we collect for the following purposes: To provide and improve our services: We use your information to provide our services to you, to personalize your experience, and to improve our services. To communicate with you: We may use your information to communicate with you about our services, to send you promotional materials, and to respond to your inquiries. To comply with legal obligations: We may use your information to comply with legal obligations, such as responding to a subpoena or court order. How we share information We may share your information with third parties in the following circumstances: With your consent: We may share your information with third parties with your consent. Service providers: We may share your information with service providers who perform services on our behalf, such as hosting, payment processing, and analytics. Business partners: We may share your information with business partners who offer services that we think may be of interest to you. Legal requirements: We may disclose your information to comply with legal requirements, such as a court order or subpoena. Security We take reasonable measures to protect the information we collect from loss, theft, misuse, and unauthorized access, disclosure, alteration, and destruction. Your choices You may opt out of receiving promotional emails from us by following the instructions in those emails. If you opt out, we may still send you non-promotional emails, such as those about your account or our ongoing business relations. Updates to this policy We may update this Privacy Policy from time to time. If we make material changes to this policy, we will notify you by email or by posting a notice on our website. Contact us If you have any questions or concerns about this Privacy Policy or our practices, please contact us at [https://chat.whatsapp.com/GINWweXmcjYEsG55SHbyPB]. Thank you for using our application.";
}
